In [1]:
#Qst1
l=[]
for i in range(2000,3201):
    if (i%7==0)&(i%5!=0):
        l.append(i)
print (l)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [2]:
#Qst2
fact=1
n = int(input("Enter a number: "))
if n==0:
    print("The factorial of 0 is 1")
if n>1:
    for i in range (1,n + 1):
        fact=fact*i
    print ("The factorial of",n, "is", fact) 

Enter a number: 5
The factorial of 5 is 120


In [3]:
#Qst2
fact=1
n = int(input("Enter a number: "))
if n==0:
    print("The factorial of 0 is 1")
if n>1:
    for i in range (1,n + 1):
        fact=fact*i
    print ("The factorial of",n, "is", fact)

Enter a number: 0
The factorial of 0 is 1


In [4]:
#Qst3
n = int(input("Enter a number: "))
dict={i:i*i for i in range(1,n+1)}
print (dict)

Enter a number: 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [5]:
#Qst4
s=input("Enter a string ")
ss=''
if (s==ss):
    print("Enter a non-empty string !")
else:
    for n in range(0,len(s)-1):
        n=int(input("Enter a number "))
        new=s[:n]+s[n+1:]
        print (new)

Enter a string 1


In [ ]:
#Qst4
s=input("Enter a string ")
ss=''
if (s==ss):
    print("Enter a non-empty string !")
else:
    for n in range(0,len(s)-1):
        n=int(input("Enter a number "))
        new=s[:n]+s[n+1:]
        print (new)

Enter a string Myriame
Enter a number 1
Mriame


In [1]:
#Qst5
import numpy as np
n= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(n)
print("Array to list:")
print(n.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [2]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [3]:
#Qst7
import math
C=50
H=30
numbers = input("Enter D ")
numbers = numbers.split(',')

result= []
for D in numbers:
    Q = round(math.sqrt(2 * C * int(D) / H))
    result.append(Q)

print(result)

Enter D 100,150,180
[18, 22, 24]
